# Generated by Django 3.2.7 on 2024-03-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240315_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgrounduser',
            options={'ordering': ['-pk']},
        ),
    ]
